import type { Metadata } from "next";

import "./globals.css";
import Header from "../components/Header";
import Transition from "@/components/Transition";
import Footer from "@/components/Footer";
import { Providers } from "./Provider";

export const metadata: Metadata = {
  title: "Rare Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Transition>{children}</Transition>
        </Providers>
      </body>
    </html>
  );
}
